contact         : "info@software-carpentry.org"
facebook_url    : "https://www.facebook.com/SoftwareCarpentry"
github_url      : "https://github.com/swcarpentry"
google_plus_url : "https://plus.google.com/u/0/114244759874490019250/posts"
rss_url         : "http://software-carpentry.org/feed.xml"
twitter_name    : "@swcarpentry"
twitter_url     : "https://twitter.com/swcarpentry"
recent_length   : 10
blog_title      : "Software Carpentry"
blog_subtitle   : "Helping scientists make better software since 1998"
training_url    : "http://teaching.software-carpentry.org"
listserv_url    : "http://lists.software-carpentry.org/listinfo.cgi"
flag_size       : 16
admin_overhead  : $1500
badges : {
    "creator" : [
        {"user" : "crouch.s", "name" : "Steve Crouch"},
        {"user" : "guy.t", "name" : "Richard 'Tommy' Guy"},
        {"user" : "jackson.m", "name" : "Mike Jackson"},
        {"user" : "montojo.j", "name" : "Jason Montojo"},
        {"user" : "pipitone.j", "name" : "Jon Pipitone"},
        {"user" : "white.e", "name" : "Ethan White"},
        {"user" : "wilson.g", "name" : "Greg Wilson"}
    ],
    "instructor" : [
        {"user" : "ahmadia.a", "name" : "Aron Ahmadia"},
        {"user" : "anderson.c", "name" : "Carlos Anderson"},
        {"user" : "aruliah.d", "name" : "Dhavide Aruliah"},
        {"user" : "barneche.diego", "name" : "Diego Barneche"},
        {"user" : "blischak.j", "name" : "John Blischak"},
        {"user" : "bostroem.a", "name" : "Azalee Bostroem"},
        {"user" : "bray.e", "name" : "Erik Bray"},
        {"user" : "brown.ct", "name" : "C. Titus Brown"},
        {"user" : "bryan.j", "name" : "Jennifer Bryan"},
        {"user" : "canino-koning.r", "name" : "Rosangela Canino-Koning"},
        {"user" : "cannam.c", "name" : "Chris Cannam"},
        {"user" : "cholia.s", "name" : "Shreyas Cholia"},
        {"user" : "chuang-howe.a", "name" : "Adina Chuang Howe"},
        {"user" : "chue-hong.n", "name" : "Neil Chue Hong"},
        {"user" : "cozzini.s", "name" : "Stefano Cozzini"},
        {"user" : "crouch.s", "name" : "Steve Crouch"},
        {"user" : "davis.m", "name" : "Matt Davis"},
        {"user" : "dickson.r", "name" : "Ross Dickson"},
        {"user" : "dursi.j", "name" : "Jonathan Dursi"},
        {"user" : "ely.j", "name" : "Justin Ely"},
        {"user" : "enbody.r", "name" : "Richard Enbody"},
        {"user" : "falster.daniel", "name" : "Daniel Falster"},
        {"user" : "figueira.l", "name" : "Luis Figueira"},
        {"user" : "fitzjohn.rich", "name" : "Rich FitzJohn"},
        {"user" : "gustavsen.j", "name" : "Julia Gustavsen"},
        {"user" : "guy.t", "name" : "Richard 'Tommy' Guy"},
        {"user" : "haddock.s", "name" : "Steve Haddock"},
        {"user" : "hansen.m", "name" : "Mike Hansen"},
        {"user" : "hart.t", "name" : "Ted Hart"},
        {"user" : "hinsen.k", "name" : "Konrad Hinsen"},
        {"user" : "huff.k", "name" : "Katy Huff"},
        {"user" : "ivanov.p", "name" : "Paul Ivanov"},
        {"user" : "jackson.m", "name" : "Mike Jackson"},
        {"user" : "jones.d", "name" : "David Jones"},
        {"user" : "kerr.j", "name" : "Jessica Kerr"},
        {"user" : "kitzes.j", "name" : "Justin Kitzes"},
        {"user" : "koenig.steven", "name" : "Steven Koenig"},
        {"user" : "konrad.b", "name" : "Bernhard Konrad"},
        {"user" : "lagesen.k", "name" : "Karin Lagesen"},
        {"user" : "langmore.i", "name" : "Ian Langmore"},
        {"user" : "lasher.c", "name" : "Chris Lasher"},
        {"user" : "latornell.d", "name" : "Doug Latornell"},
        {"user" : "mcgough.s", "name" : "Stephen McGough"},
        {"user" : "mckellar.j", "name" : "Jessica McKellar"},
        {"user" : "mctavish.ej", "name" : "Emily Jane McTavish"},
        {"user" : "mitchell.i", "name" : "Ian Mitchell"},
        {"user" : "morris.b", "name" : "Ben Morris"},
        {"user" : "nederbragt.l", "name" : "Lex Nederbragt"},
        {"user" : "olson.r", "name" : "Randy Olson"},
        {"user" : "pawlik.a", "name" : "Aleksandra Pawlik"},
        {"user" : "pell.j", "name" : "Jason Pell"},
        {"user" : "perez.f", "name" : "Fernando Perez"},
        {"user" : "pickens.c", "name" : "Caitlyn Pickens"},
        {"user" : "ram.k", "name" : "Karthik Ram"},
        {"user" : "rokem.a", "name" : "Ariel Rokem"},
        {"user" : "schossau.j", "name" : "Jorden Schossau"},
        {"user" : "scopatz.a", "name" : "Anthony Scopatz"},
        {"user" : "shelton.j", "name" : "Jeff Shelton"},
        {"user" : "smith.j", "name" : "Joshua Ryan Smith"},
        {"user" : "supp.s", "name" : "Sarah Supp"},
        {"user" : "teal.t", "name" : "Tracy Teal"},
        {"user" : "trimble.will", "name" : "Will Trimble"},
        {"user" : "varoquaux.n", "name" : "Nelle Varoquaux"},
        {"user" : "vera.b", "name" : "Bogdan Vera"},
        {"user" : "viana.a", "name" : "Alex Viana"},
        {"user" : "vonderlinden.jens", "name" : "Jens von der Linden"},
        {"user" : "waugh.b", "name" : "Ben Waugh"},
        {"user" : "white.e", "name" : "Ethan White"},
        {"user" : "williams.l", "name" : "Lynne Williams"},
        {"user" : "wilson.g", "name" : "Greg Wilson"},
        {"user" : "woods.c", "name" : "Chris Woods"}
    ],
    "organizer" : [
        {"user" : "aranda.j", "name" : "Jorge Aranda"},
        {"user" : "bergman.c", "name" : "Casey Bergman"},
        {"user" : "berriman.b", "name" : "Bruce Berriman"},
        {"user" : "broekmans.o", "name" : "Onno Broekmans"},
        {"user" : "brown.amy", "name" : "Amy Brown"},
        {"user" : "chartier.a", "name" : "Alex Chartier"},
        {"user" : "cholia.s", "name" : "Shreyas Cholia"},
        {"user" : "cozzini.s", "name" : "Stefano Cozzini"},
        {"user" : "dickson.r", "name" : "Ross Dickson"},
        {"user" : "ellis.dan", "name" : "Dan Ellis"},
        {"user" : "fowler.p", "name" : "Philip Fowler"},
        {"user" : "goble.c", "name" : "Carole Goble"},
        {"user" : "gray.c", "name" : "Chris Gray"},
        {"user" : "hetherington.james", "name" : "James Hetherington"},
        {"user" : "howe.b", "name" : "Bill Howe"},
        {"user" : "irving.d", "name" : "Damien Irving"},
        {"user" : "kooyers.n", "name" : "Nic Kooyers"},
        {"user" : "langmore.i", "name" : "Ian Langmore"},
        {"user" : "lu.p", "name" : "Paul Lu"},
        {"user" : "lumsdaine.a", "name" : "Andrew Lumsdaine"},
        {"user" : "madin.j", "name" : "Joshua Madin"},
        {"user" : "marchewka.damian", "name" : "Damian Marchewka"},
        {"user" : "mitchell.i", "name" : "Ian M. Mitchell"},
        {"user" : "montojo.j", "name" : "Jason Montojo"},
        {"user" : "nederbragt.l", "name" : "Lex Nederbragt"},
        {"user" : "paciorek.c", "name" : "Chris Paciorek"},
        {"user" : "petre.m", "name" : "Marian Petre"},
        {"user" : "pipitone.j", "name" : "Jon Pipitone"},
        {"user" : "plumbley.m", "name" : "Mark Plumbley"},
        {"user" : "rezny.m", "name" : "Michael Rezny"},
        {"user" : "schutt.r", "name" : "Rachel Schutt"},
        {"user" : "shelton.j", "name" : "Jeff Shelton"},
        {"user" : "su.a", "name" : "Andrew Su"},
        {"user" : "vision.t", "name" : "Todd Vision"},
        {"user" : "waugh.b", "name" : "Ben Waugh"},
        {"user" : "white.e", "name" : "Ethan White"},
        {"user" : "wilson.g", "name" : "Greg Wilson"},
        {"user" : "wilson.p", "name" : "Paul Wilson"},
        {"user" : "wilson.r", "name" : "Robin Wilson"},
        {"user" : "wolever.d", "name" : "David Wolever"}
    ]
}
