contact         : "info@software-carpentry.org"
facebook_url    : "https://www.facebook.com/SoftwareCarpentry"
github_url      : "https://github.com/swcarpentry"
google_plus_url : "https://plus.google.com/u/0/114244759874490019250/posts"
rss_url         : "http://software-carpentry.org/feed.xml"
twitter_name    : "@swcarpentry"
twitter_url     : "https://twitter.com/swcarpentry"
recent_length   : 10
blog_title      : "Software Carpentry"
blog_subtitle   : "Helping scientists make better software since 1998"
training_url    : "http://teaching.software-carpentry.org"
listserv_url    : "http://lists.software-carpentry.org/listinfo.cgi"
flag_size       : 16
admin_overhead  : $1500
exclude         : [standard_config.yml, badges_config.yml]
colors          : {past : FE7070, open : 70FE80, full : FEFE70, restricted : 7070FE, instructor : 70FEFE}
