- https://github.com/arokem/2014-01-27-Stanford
- https://github.com/jennybc/2014-01-27-miami
- https://github.com/uiuc-cse/2014-01-30-cse
- https://github.com/geocarpentry/2014-01-30-mit
- https://github.com/swcarpentry/2014-01-31-ucsb
- https://github.com/apawlik/2014-02-03-TGAC
- https://github.com/damienirving/2014-02-10-hobart
- https://github.com/swcarpentry/2014-02-11-toronto
- https://github.com/bernhardkonrad/2014-02-22-SFU
- https://github.com/swcarpentry/2014-02-15-umkc
- https://github.com/nicercode/2014-02-13-UNSW
- https://github.com/nicercode/2014-02-18-UTS
- https://github.com/swcarpentry/2014-02-18-aims
- https://github.com/apawlik/2014-02-18-UCL
- https://github.com/justincely/2014-02-24-esac
- https://github.com/swcarpentry/2014-02-28-ethz
- https://github.com/synesthesiam/2014-03-10-uva
- https://github.com/swcarpentry/2014-03-17-nyu
- https://github.com/swcarpentry/2014-03-17-ucb
- https://github.com/ljwilliams/2014-03-17-uw
- https://github.com/swcarpentry/2014-03-17-purdue
- https://github.com/resbaz/2014-03-18-combine
- https://github.com/swcarpentry/2014-04-02-uvic
- https://github.com/luispedro/2014-04-03-sdu
- https://github.com/jduckles/2014-04-04-ou
- https://github.com/emhart/2014-04-09-ucar
- https://github.com/apawlik/2014-04-09-GARNET
- https://github.com/swcarpentry/2014-04-14-wise
- https://github.com/swcarpentry/2014-04-14-pycon
- https://github.com/dhavide/2014-04-14-pycon-lib
- https://github.com/swcarpentry/2014-04-14-pycon-ngs
- https://github.com/swcarpentry/2014-04-14-pycon-r
- https://github.com/gvwilson/2014-04-14-pycon-teach
- https://github.com/swcarpentry/2014-04-28-training
- https://github.com/elixirno/2014-04-23-uib
- https://github.com/jrherr/2014-04-29-gwu
- https://github.com/DevasenaInupakutika/2014-05-08-soton
- https://github.com/wltrimbl/2014-05-12-cshl
- https://github.com/r-gaia-cs/2014-05-12-furg
- https://github.com/swcarpentry/2014-05-12-oicr-toronto
- https://github.com/jennybc/2014-05-12-ubc
- https://github.com/geocarpentry/2014-05-23-csdms
- https://github.com/badger-d/2014-06-02-monash
- https://github.com/apawlik/2014-06-03-cern
- https://github.com/BernhardKonrad/2014-06-16-davis
- https://github.com/swcarpentry/2014-06-16-toronto
- https://github.com/guyrt/2014-07-08-stonybrook
- https://github.com/vu-bc/2014-08-12-vu
